In [1]:
import pandas as pd
import numpy as np

In [2]:
from pathlib import Path

In [3]:
data_dir = Path(
    "/Users/jeffnewman/Library/CloudStorage/OneDrive-SharedLibraries-CambridgeSystematics"
    "/PROJ 210048 - Ohio DOT Modeling Support - ASim-LongDist/ValidationData/Files/LDT_Survey"
)

In [4]:
tour_patterns = pd.read_csv(data_dir/"tour_patterns.csv")

In [5]:
tour_patterns

,hh_id,per_id,tour,oneday,purpose,pattern,type,anchor_taz,dest_taz,anchor_type,...,tour_dept,tour_dept_day,tour_arr,tour_arr_day,dest_arr,dest_arr_day,dest_dept,dest_dept_day,survey_start,survey_end
0,5016239,2,1,0,H,hov,0.0,9087.0,87032.0,5.0,...,2003-Oct-25T06:00,7.0,2003-Nov-09T23:59,1.0,2003-Oct-25T09:00,7.0,2003-Oct-26T19:00,1.0,2003-Oct-13T00:00,2003-Nov-09T23:59
1,5016239,1,1,0,H,hov,0.0,9087.0,87032.0,5.0,...,2003-Oct-25T06:00,7.0,2003-Nov-09T23:59,1.0,2003-Oct-25T09:00,7.0,2003-Oct-26T19:00,1.0,2003-Oct-13T00:00,2003-Nov-09T23:59
2,4039961,2,1,0,O,homv,0.0,31169.0,98007.0,5.0,...,2003-Apr-20T13:30,1.0,2003-May-06T23:59,3.0,2003-Apr-21T20:00,2.0,2003-Apr-27T07:10,1.0,2003-Apr-07T00:00,2003-May-06T23:59
3,4039961,4,1,0,O,homv,0.0,31169.0,98007.0,5.0,...,2003-Apr-20T13:30,1.0,2003-May-06T23:59,3.0,2003-Apr-21T20:00,2.0,2003-Apr-27T07:10,1.0,2003-Apr-07T00:00,2003-May-06T23:59
4,4039961,1,1,1,O,hok,0.0,31169.0,57086.0,5.0,...,2003-Apr-08T07:30,3.0,2003-Apr-08T07:30,3.0,2003-Apr-08T08:45,3.0,2003-Apr-08T07:30,3.0,2003-Apr-07T00:00,2003-May-06T23:59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8117,5001037,1,6,0,O,vov,0.0,77022.0,95605.0,5.0,...,2003-Oct-29T08:00,4.0,2003-Nov-02T23:59,1.0,2003-Oct-29T10:30,4.0,2003-Oct-29T14:00,4.0,2003-Oct-06T00:00,2003-Nov-02T23:59
8118,4014319,2,1,0,O,hov,0.0,83053.0,90932.0,5.0,...,2003-Oct-10T06:30,6.0,2003-Oct-19T23:59,1.0,2003-Oct-10T10:15,6.0,2003-Oct-12T18:00,1.0,2003-Sep-22T00:00,2003-Oct-19T23:59
8119,4014319,4,1,0,O,hov,0.0,83053.0,90932.0,5.0,...,2003-Oct-10T06:30,6.0,2003-Oct-19T23:59,1.0,2003-Oct-10T10:15,6.0,2003-Oct-10T18:00,6.0,2003-Sep-22T00:00,2003-Oct-19T23:59
8120,4014319,1,1,0,O,hov,0.0,83053.0,90932.0,5.0,...,2003-Oct-10T06:30,6.0,2003-Oct-19T23:59,1.0,2003-Oct-10T10:15,6.0,2003-Oct-12T18:00,1.0,2003-Sep-22T00:00,2003-Oct-19T23:59
8121,4014319,3,1,0,O,hov,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN